// Default attendance policy settings
export const DEFAULT_ATTENDANCE_SETTINGS = {
    STANDARD_HOURS_PER_DAY: 8,
    WORKING_DAYS_PER_WEEK: 5,
    OVERTIME_RATE_MULTIPLIER: 1.5,
    LATE_ARRIVAL_GRACE_PERIOD: 15, // minutes
    ATTENDANCE_BONUS_THRESHOLD: 100, // percentage
    HOURS_CONCESSION_PERCENTAGE: 10,
    SHORTFALL_DEDUCTION_PERCENTAGE: 30,
};
