// Export all DTOs
export * from './base-dto';
export * from './common-dto';
export * from './audit-dto';
export * from './document-dto';
export * from './furniture-dto';
export * from './hardwareTransfer-dto';
export * from './telex-transfer-dto';
export * from './iso-dto';
export * from './license-dto';
export * from './network-equipment-dto';
export * from './newhardware-dto';
export * from './sim-dto';
export * from './software-dto';
export * from './support-dto';
export * from './property-dto';
export * from './vehicle-dto';
